import { readFile } from "fs/promises";
import path from "path";
import type { ActivityEntry } from "@/lib/radicle";

type SnapshotFile = {
  entries?: unknown[];
};

function isActivityEntry(x: unknown): x is ActivityEntry {
  if (!x || typeof x !== "object") return false;
  const o = x as Record<string, unknown>;
  const c = o.commit;
  if (!c || typeof c !== "object") return false;
  const commit = c as Record<string, unknown>;
  const committer = commit.committer;
  if (!committer || typeof committer !== "object") return false;
  const t = (committer as { time?: unknown }).time;
  const summary = commit.summary;
  const summaryOk =
    summary === undefined ||
    summary === null ||
    typeof summary === "string";
  return (
    typeof o.rid === "string" &&
    typeof o.repoName === "string" &&
    typeof commit.id === "string" &&
    summaryOk &&
    typeof t === "number"
  );
}

function normalizeEntries(data: unknown): unknown[] | null {
  if (Array.isArray(data)) return data;
  if (data && typeof data === "object" && Array.isArray((data as SnapshotFile).entries)) {
    return (data as SnapshotFile).entries!;
  }
  return null;
}

/** Relative paths: try cwd, then cwd/dashboard (repo root vs dashboard/). */
function candidatePaths(rel: string): string[] {
  const cwd = process.cwd();
  const out: string[] = [];
  out.push(path.join(cwd, rel));
  if (!rel.startsWith("..")) {
    out.push(path.join(cwd, "dashboard", rel));
  }
  return [...new Set(out)];
}

/**
 * Optional JSON snapshot of profile activity (heatmap + recent commits).
 * Set `RADICLE_ACTIVITY_SNAPSHOT_PATH` to an absolute path, or a path relative
 * to `process.cwd()` (often `dashboard/` when you `cd dashboard` before
 * `npm start`, but sometimes the repo root — we try both).
 *
 * Generated by `scripts/export-activity-snapshot.mjs` on the machine whose
 * `radicle-httpd` has your latest commits (e.g. M1), then copy the file to M3.
 */
export async function readActivitySnapshot(): Promise<ActivityEntry[] | null> {
  const raw = process.env.RADICLE_ACTIVITY_SNAPSHOT_PATH?.trim();
  if (!raw) return null;

  const paths = path.isAbsolute(raw) ? [raw] : candidatePaths(raw);

  let buf: string | null = null;
  for (const filePath of paths) {
    try {
      buf = await readFile(filePath, "utf8");
      break;
    } catch {
      /* try next */
    }
  }
  if (buf === null) return null;

  try {
    const data = JSON.parse(buf) as unknown;
    const rawEntries = normalizeEntries(data);
    if (!rawEntries) return null;
    const entries = rawEntries.filter(isActivityEntry) as ActivityEntry[];
    if (entries.length === 0) return null;
    const normalized: ActivityEntry[] = entries.map((e) => ({
      ...e,
      commit: {
        ...e.commit,
        summary:
          e.commit.summary === undefined || e.commit.summary === null
            ? ""
            : e.commit.summary,
      },
    }));
    return normalized.sort(
      (a, b) => b.commit.committer.time - a.commit.committer.time,
    );
  } catch {
    return null;
  }
}
