import { readFile } from "fs/promises";
import path from "path";
import {
  normalizeCommitterTimeSeconds,
  type ActivityEntry,
} from "@/lib/radicle";

function isActivityEntry(x: unknown): x is ActivityEntry {
  if (!x || typeof x !== "object") return false;
  const o = x as Record<string, unknown>;
  const c = o.commit;
  if (!c || typeof c !== "object") return false;
  const commit = c as Record<string, unknown>;
  const committer = commit.committer;
  if (!committer || typeof committer !== "object") return false;
  const t = (committer as { time?: unknown }).time;
  const timeOk = normalizeCommitterTimeSeconds(t) !== null;
  const summary = commit.summary;
  const summaryOk =
    summary === undefined ||
    summary === null ||
    typeof summary === "string";
  const id =
    typeof commit.id === "string" && commit.id
      ? commit.id
      : typeof commit.sha === "string" && commit.sha
        ? commit.sha
        : null;
  return (
    typeof o.rid === "string" &&
    typeof o.repoName === "string" &&
    id !== null &&
    summaryOk &&
    timeOk
  );
}

function normalizeEntries(data: unknown): unknown[] | null {
  if (Array.isArray(data)) return data;
  if (data && typeof data === "object") {
    const o = data as Record<string, unknown>;
    if (Array.isArray(o.entries)) return o.entries as unknown[];
    if (Array.isArray(o.commits)) return o.commits as unknown[];
    if (Array.isArray(o.activity)) return o.activity as unknown[];
  }
  return null;
}

/** Relative paths: `cwd`, `cwd/dashboard`, and `cwd/..` (repo root when cwd is `dashboard/`). */
function candidatePaths(rel: string): string[] {
  const cwd = process.cwd();
  const out: string[] = [];
  out.push(path.join(cwd, rel));
  if (!rel.startsWith("..")) {
    out.push(path.join(cwd, "dashboard", rel));
    out.push(path.join(cwd, "..", rel));
  }
  return [...new Set(out)];
}

/**
 * Optional JSON snapshot of profile activity (heatmap + recent commits).
 * Set `RADICLE_ACTIVITY_SNAPSHOT_PATH` to an absolute path, or a path relative
 * to `process.cwd()` (often `dashboard/` when you `cd dashboard` before
 * `npm start`, but sometimes the repo root — we try both).
 *
 * Generated by `scripts/export-activity-snapshot.mjs` on the machine whose
 * `radicle-httpd` has your latest commits (e.g. M1), then copy the file to M3.
 * `committer.time` may be Unix seconds, ms (≥1e12), or an ISO-8601 string.
 */
export async function readActivitySnapshot(): Promise<ActivityEntry[] | null> {
  const raw = process.env.RADICLE_ACTIVITY_SNAPSHOT_PATH?.trim();
  if (!raw) return null;

  const paths = path.isAbsolute(raw) ? [raw] : candidatePaths(raw);

  let buf: string | null = null;
  for (const filePath of paths) {
    try {
      buf = await readFile(filePath, "utf8");
      break;
    } catch {
      /* try next */
    }
  }
  if (buf === null) return null;

  try {
    const data = JSON.parse(buf) as unknown;
    const rawEntries = normalizeEntries(data);
    if (!rawEntries) return null;
    const entries = rawEntries.filter(isActivityEntry) as ActivityEntry[];
    if (entries.length === 0) return null;
    const normalized: ActivityEntry[] = [];
    for (const e of entries) {
      const rawCommit = e.commit as Record<string, unknown>;
      const commitId =
        typeof e.commit.id === "string" && e.commit.id
          ? e.commit.id
          : typeof rawCommit.sha === "string" && rawCommit.sha
            ? rawCommit.sha
            : "";
      if (!commitId) continue;
      const rawTs = e.commit.committer.time;
      const ts = normalizeCommitterTimeSeconds(rawTs);
      if (ts === null || !Number.isFinite(ts)) continue;
      normalized.push({
        ...e,
        commit: {
          ...e.commit,
          id: commitId,
          summary:
            e.commit.summary === undefined || e.commit.summary === null
              ? ""
              : e.commit.summary,
          committer: { ...e.commit.committer, time: ts },
        },
      });
    }
    if (normalized.length === 0) return null;
    const sorted = normalized.sort(
      (a, b) => b.commit.committer.time - a.commit.committer.time,
    );
    const seen = new Set<string>();
    return sorted.filter((e) => {
      const k = `${e.rid}:${e.commit.id}`;
      if (seen.has(k)) return false;
      seen.add(k);
      return true;
    });
  } catch {
    return null;
  }
}
